#### GLOBAL SECTION 

[global]

log_level = 'debug'

[mode]

[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = false

[mode.channels]
enabled = false

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true
tx_confirmation = false
auto_register_counterparty_payee = false

[rest]
enabled = false
host = '127.0.0.1'
port = 3000

[telemetry]
enabled = false
host = '127.0.0.1'
port = 3001


#### CHAIN-SPECIFIC SECTION: Cosmoshub Testnet

[[chains]]
id = 'theta-testnet-001'

# event source configuration
event_source = { mode = 'pull', interval = '1000ms' }
rpc_addr = 'https://rpc.sentry-01.theta-testnet.polypore.xyz:443'
grpc_addr = 'https://grpc.sentry-01.theta-testnet.polypore.xyz:443'
rpc_timeout = '10s'

# account settings
account_prefix = 'cosmos'
key_name = 'test-relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'

# tx fee & gas settings
default_gas = 2000000
max_gas = 30000000
gas_price = { price = 0.026, denom = 'uatom' }
gas_multiplier = 1.2
dynamic_gas_price = { enabled = true, multiplier = 1.1, max = 0.1 }
max_msg_num = 25
max_tx_size = 1500000

# ibc lighclient settings
clock_drift = '15s'
max_block_time = '10s'
# trusting_period = '40h'
trust_threshold = { numerator = '2', denominator = '3' }
client_refresh_rate = '1/8'

# custom memo
memo_prefix = ''

# packet filter
# [chains.packet_filter]
# policy = 'allow'
# list = [

# ]


#### CHAIN-SPECIFIC SECTION: Neutron Testnet

[[chains]]
id = 'pion-1'
ccv_consumer_chain = true

# event source configuration
event_source = { mode = 'pull', interval = '1000ms' }
rpc_addr = 'https://rpc-palvus.pion-1.ntrn.tech:443'
grpc_addr = 'http://neutron-testnet-grpc.polkachu.com:19190'
rpc_timeout = '10s'

# account settings
account_prefix = 'neutron'
key_name = 'test-relayer'
address_type = { derivation = 'cosmos' }
store_prefix = 'ibc'

# tx fee & gas settings
default_gas = 2000000
max_gas = 20000000
gas_price = { price = 0.1, denom = 'untrn' }
gas_multiplier = 1.2
dynamic_gas_price = { enabled = true, multiplier = 1.1, max = 1 }
max_msg_num = 25
max_tx_size = 1500000

# ibc lighclient settings
clock_drift = '5s'
max_block_time = '10s'
# trusting_period = '336h'
trust_threshold = { numerator = '2', denominator = '3' }
client_refresh_rate = '1/30'

# custom memo
memo_prefix = ''

# packet filter
# [chains.packet_filter]
# policy = 'allow'
# list = [

# ]

